//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public int rowid { get; set; }
        public string placa { get; set; }
        public bool oficial { get; set; }
        public System.DateTime fecha_entrada { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public double tarifa { get; set; }
    }
}
